version: "1.5.1rc0"

components:
  - name: MyDocumentStore
    type: ElasticsearchDocumentStore
    params:
      embedding_dim: 384
      index: bm_documents
      port: 9200
      similarity: cosine
  - name: MyReader
    type: FARMReader
    params:
      no_ans_boost: -10
      model_name_or_path: deepset/roberta-base-squad2
  - name: MyESRetriever
    type: BM25Retriever
    params:
      document_store: MyDocumentStore

pipelines:
  - name: my_query_pipeline
    nodes:
      - name: MyESRetriever
        inputs: [ Query ]
      - name: MyReader
        inputs: [ MyESRetriever ]
